//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCF_SV")]
    public interface IWCF_SV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/getAllSV", ReplyAction="http://tempuri.org/IWCF_SV/getAllSVResponse")]
        DTO.SV_DTO[] getAllSV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/getAllSV", ReplyAction="http://tempuri.org/IWCF_SV/getAllSVResponse")]
        System.Threading.Tasks.Task<DTO.SV_DTO[]> getAllSVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/themSV", ReplyAction="http://tempuri.org/IWCF_SV/themSVResponse")]
        bool themSV(DTO.SV_DTO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/themSV", ReplyAction="http://tempuri.org/IWCF_SV/themSVResponse")]
        System.Threading.Tasks.Task<bool> themSVAsync(DTO.SV_DTO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/suaSV", ReplyAction="http://tempuri.org/IWCF_SV/suaSVResponse")]
        bool suaSV(DTO.SV_DTO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/suaSV", ReplyAction="http://tempuri.org/IWCF_SV/suaSVResponse")]
        System.Threading.Tasks.Task<bool> suaSVAsync(DTO.SV_DTO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/xoaSV", ReplyAction="http://tempuri.org/IWCF_SV/xoaSVResponse")]
        bool xoaSV(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_SV/xoaSV", ReplyAction="http://tempuri.org/IWCF_SV/xoaSVResponse")]
        System.Threading.Tasks.Task<bool> xoaSVAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCF_SVChannel : GUI.ServiceReference1.IWCF_SV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_SVClient : System.ServiceModel.ClientBase<GUI.ServiceReference1.IWCF_SV>, GUI.ServiceReference1.IWCF_SV {
        
        public WCF_SVClient() {
        }
        
        public WCF_SVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCF_SVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_SVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_SVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTO.SV_DTO[] getAllSV() {
            return base.Channel.getAllSV();
        }
        
        public System.Threading.Tasks.Task<DTO.SV_DTO[]> getAllSVAsync() {
            return base.Channel.getAllSVAsync();
        }
        
        public bool themSV(DTO.SV_DTO sv) {
            return base.Channel.themSV(sv);
        }
        
        public System.Threading.Tasks.Task<bool> themSVAsync(DTO.SV_DTO sv) {
            return base.Channel.themSVAsync(sv);
        }
        
        public bool suaSV(DTO.SV_DTO sv) {
            return base.Channel.suaSV(sv);
        }
        
        public System.Threading.Tasks.Task<bool> suaSVAsync(DTO.SV_DTO sv) {
            return base.Channel.suaSVAsync(sv);
        }
        
        public bool xoaSV(string id) {
            return base.Channel.xoaSV(id);
        }
        
        public System.Threading.Tasks.Task<bool> xoaSVAsync(string id) {
            return base.Channel.xoaSVAsync(id);
        }
    }
}
